### ISSUE TITLE
Remove kerberos server with LDAP DB functionality

### ISSUE THREAD

**Issue by Firstyear** [yast/yast-auth-server#73]
It seems that some of the krb functionality hasn't worked cleanly for about 2 years. Because of the lack of issues raised about this, I can only assume this feature is *not* used widely.

As a result I would like to remove it. We should not be recommending kerberos in 2022 due to it's complexity and risk. 

This will mean you can no longer setup new kerberos databases that are ldap backend via yast. Existing instals will keep working, and new installs will need to be configured by hand.

**Comment by kenaaker** [comment]
Removing Kerberos would be counter productive, I suspect.  I think that Active Directory is a Kerberos implementation, so if you remove "Kerberos" functionality, you might lose the ability to interact with Active Directory.

**Comment by Firstyear** [comment]
No, there is specific functionality for AD with SSSD and winbind. This is for 389-ds to setup an internal krb server instead, whcih has been non-functional for a long time.

**Comment by Firstyear** [comment]
Not quite @kenaaker  - sssd is the *client* half of the equation that allows a workstation or server to communicate to kerberos/ldap for authentication and identity information. 

Kerberos only provides authentication (verification of an identity) and only does so with a password. It was designed in a era pre-TLS so it assumes there is no safe network transport. It also enables credential caching via a ticket system, which then can be forwarded to other machines. This has caused some of the most damage to IT systems globally, especially through microsoft environments that use kerberos due to unconstrained lateral movement, making kerberos likely one of the most damaging technologies to ever exist. 

LDAP provides authentication and identity info, as well as database replication. In this yast feature, it allows storing the kerberos database (normally only on a single machine as krb has no replication features), into ldap to "piggy back" off of ldaps ability to do replication. 

However, it's been broken for literally years - attempting to setup and use this feature via this module would never result in a working configuration. Because of that, it failed the "scream" test, where no on complained about it. The first report of a problem, was via internal SUSE QA noticing it failing, which promtped the talk to remove it.

**Comment by Firstyear** [comment]
@kenaaker Do you mind emailing me directly about your auth server issues? I'd be happy to help out william.brown at suse.com :)

**Comment by suntorytimed** [comment]
As this removal is now landing in 15 SP5 and we don't have a feature for it to document the change I have opened a Bugzilla documentation bug to make sure we have that in our Release Notes. https://bugzilla.suse.com/show_bug.cgi?id=1202257
